ALTER TABLE DETAILITEM
ADD TAX DECIMAL(12, 2),
ADD NETPRICE DECIMAL(12, 2);

UPDATE DETAILITEM
SET
    TAX = CASE
        WHEN TOTALPRICE >= 100000 THEN TOTALPRICE * 0.12
        ELSE 0
    END;

UPDATE DETAILITEM SET NETPRICE = TOTALPRICE + TAX;