SELECT R.CUSTOMERNAME, D.ALBUMNO, A.PRICE, D.NETPRICE * 0.9 AS NETPRICE_REDUCTION
FROM
    RECEIPT R
    JOIN DETAILITEM D ON R.RECEIPTNO = D.RECEIPTNO
    JOIN ALBUM A ON D.ALBUMNO = A.ALBUMNO
WHERE
    `RELEASEYEAR` < 2017