-- Active: 1728814371862@@127.0.0.1@3306@OWNER
CREATE DATABASE CDM;

CREATE TABLE JENIS_LAYANAN (
    JL_ID VARCHAR(5) PRIMARY KEY NOT NULL,
    JL_NAMA VARCHAR(100) NOT NULL,
    JL_HARGA DECIMAL(6, 2) NOT NULL
);

CREATE TABLE NOTA (
    N_NO INTEGER PRIMARY KEY NOT NULL,
    N_TGLMASUK DATE NOT NULL,
    N_TGLPERKIRAANSELESAI DATE NOT NULL,
    N_TGLSELESAI DATE,
    N_TGLAMBIL TIMESTAMP,
    N_STATUS VARCHAR(10) NOT NULL,
    N_KODERAK VARCHAR(3)
);

CREATE TABLE KARYAWAN (
    K_ID CHARACTER(2) PRIMARY KEY NOT NULL,
    K_NAMA VARCHAR(100) NOT NULL,
    K_BAGIAN VARCHAR(25),
    K_TGLMASUK DATE,
    K_EMAIL VARCHAR(100) NOT NULL,
    K_PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE PELANGGAN (
    P_NO CHAR(5) PRIMARY KEY NOT NULL,
    P_NAMA VARCHAR(60) NOT NULL,
    P_JENISKEL CHAR(1),
    P_TEMPATLAHIR VARCHAR(30),
    P_TGLLAHIR DATE,
    P_ALAMAT VARCHAR(200),
    P_NOTELP VARCHAR(15),
    P_TGLDAFTAR DATE NOT NULL
);

CREATE TABLE PAYMENT (
    B_NO INTEGER PRIMARY KEY NOT NULL,
    B_TOTALHARGA DECIMAL(10, 3) NOT NULL,
    B_TGLBAYAR DATE NOT NULL
)

DROP DATABASE PDM