-- Active: 1728814371862@@127.0.0.1@3306@DDL
DROP DATABASE IF EXISTS DDL;
CREATE DATABASE DDL;
USE DDL;

CREATE TABLE JENIS_LAYANAN (
    JL_ID VARCHAR(5) NOT NULL,
    JL_NAMA VARCHAR(100) NOT NULL,
    JL_HARGA DECIMAL(6, 2) NOT NULL,
    PRIMARY KEY(JL_ID)
);

CREATE TABLE KARYAWAN (
    K_ID CHARACTER(2) NOT NULL,
    K_NAMA VARCHAR(100) NOT NULL,
    K_BAGIAN VARCHAR(25),
    K_TGLMASUK DATE,
    K_EMAIL VARCHAR(100) NOT NULL,
    K_PASSWORD VARCHAR(100) NOT NULL,
    K_MANAGER_ID CHARACTER(2) NOT NULL,
    PRIMARY KEY(K_ID),
    FOREIGN KEY(K_MANAGER_ID) REFERENCES KARYAWAN(K_ID)
);

CREATE TABLE PELANGGAN (
    P_NO CHAR(5) NOT NULL,
    P_NAMA VARCHAR(60) NOT NULL,
    P_JENISKEL CHAR(1),
    P_TEMPATLAHIR VARCHAR(30),
    P_TGLLAHIR DATE,
    P_ALAMAT VARCHAR(200),
    P_NOTELP VARCHAR(15),
    P_TGLDAFTAR DATE NOT NULL,
    PRIMARY KEY(P_NO)
);

CREATE TABLE NOTA (
    N_NO INTEGER NOT NULL,
    N_TGLMASUK DATE NOT NULL,
    N_TGLPERKIRAANSELESAI DATE NOT NULL,
    N_TGLSELESAI DATE,
    N_TGLAMBIL TIMESTAMP,
    N_STATUS VARCHAR(10) NOT NULL,
    N_KODERAK VARCHAR(3),
    P_NO CHAR(5) NOT NULL,
    PRIMARY KEY(N_NO),
    FOREIGN KEY(P_NO) REFERENCES PELANGGAN(P_NO)
);

CREATE TABLE NOTA_JENIS_LAYANAN(
    N_NO INTEGER NOT NULL,
    JL_ID VARCHAR(5) NOT NULL,
    PRIMARY KEY(N_NO, JL_ID),
    FOREIGN KEY(N_NO) REFERENCES NOTA(N_NO),
    FOREIGN KEY(JL_ID) REFERENCES JENIS_LAYANAN(JL_ID)
);

CREATE TABLE NOTA_KARYAWAN(
    N_NO INTEGER NOT NULL,
    K_ID CHAR(2) NOT NULL,
    PRIMARY KEY(N_NO, K_ID),
    FOREIGN KEY(N_NO) REFERENCES NOTA(N_NO),
    FOREIGN KEY(K_ID) REFERENCES KARYAWAN(K_ID)
);

CREATE TABLE PAYMENT (
    B_NO INTEGER NOT NULL,
    B_TOTALHARGA DECIMAL(10, 3) NOT NULL,
    B_TGLBAYAR DATE NOT NULL,
    N_NO INTEGER NOT NULL,
    PRIMARY KEY(B_NO, N_NO),
    FOREIGN KEY(N_NO) REFERENCES NOTA(N_NO)
);