-- Active: 1728902121100@@127.0.0.1@3306@sbd_ddl_1
CREATE TABLE JENIS_LAYANAN(
JL_ID VARCHAR(5) NOT NULL,
JL_NAMA VARCHAR(100) NOT NULL,
JL_HARGA DECIMAL(6.2) NOT NULL,
PRIMARY KEY(JL_ID)
);

CREATE TABLE NOTA(
    N_NO INT NOT NULL,
    N_TGLMASUK DATE NOT NULL,
    N_TGLPERKIRAANSELESAI DATE NOT NULL,
    N_TGLSELESAI DATE,
    N_TGLAMBIL TIMESTAMP,
    N_STATUS VARCHAR(10) NOT NULL,
    N_KODERAK VARCHAR(3),
    PRIMARY KEY(N_NO)
);

CREATE TABLE DETIL_NOTA(
    JENIS_LAYANAN_JL_ID VARCHAR(5) NOT NULL,
    NOTA_N_NO INT NOT NULL,
    PRIMARY KEY(JENIS_LAYANAN_JL_ID, NOTA_N_NO),
    FOREIGN KEY(JENIS_LAYANAN_JL_ID) REFERENCES JENIS_LAYANAN(JL_ID),
    FOREIGN KEY(NOTA_N_NO) REFERENCES NOTA(N_NO)
);

CREATE TABLE PELANGGAN(
    P_NO CHAR(5) NOT NULL,
    P_NAMA VARCHAR(60) NOT NULL,
    P_JENISKEL CHAR(1),
    P_TEMPATLAHIR VARCHAR(30),
    P_TGLLAHIR DATE,
    P_ALAMAT VARCHAR(200),
    P_NOTELP VARCHAR(15),
    P_TGLDAFTAR DATE NOT NULL,
    PRIMARY KEY(P_NO)
);

CREATE TABLE PAYMENT(
    B_NO INT NOT NULL,
    B_TOTALHARGA DECIMAL(10.2) NOT NULL,
    B_TGLBAYAR DATE NOT NULL,
    PRIMARY KEY(B_NO),
);

ALTER TABLE PAYMENT 
    ADD NOTA_N_NO INT NOT NULL;

ALTER TABLE PAYMENT
    ADD CONSTRAINT fk_nota_n_no
    FOREIGN KEY (NOTA_N_NO) REFERENCES NOTA(N_NO);


CREATE TABLE KARYAWAN(
    K_ID CHAR(2) NOT NULL,
    K_NAMA VARCHAR(100) NOT NULL,
    K_BAGIAN VARCHAR(25),
    K_TGLMASUK DATE,
    K_EMAIL VARCHAR(100) NOT NULL,
    K_PASSWORD VARCHAR(100) NOT NULL,
    PRIMARY KEY(K_ID)
);

ALTER TABLE KARYAWAN
ADD KARYAWAN_MANAGER CHAR(2) NOT NULL;

ALTER TABLE KARYAWAN
ADD CONSTRAINT fk_karyawan_manager
FOREIGN KEY (KARYAWAN_MANAGER) REFERENCES KARYAWAN(K_ID);


CREATE TABLE MENGERJAKAN(
    NOTA_N_NO INT NOT NULL,
    KARYAWAN_K_ID CHAR(2) NOT NULL,
    PRIMARY KEY(NOTA_N_NO, KARYAWAN_K_ID),
    FOREIGN KEY (NOTA_N_NO) REFERENCES NOTA(N_NO),
    FOREIGN KEY (KARYAWAN_K_ID) REFERENCES KARYAWAN(K_ID)
);


