# 3
SELECT DISTINCT
    R.CUSTOMERNAME
FROM
    RECEIPT R
    JOIN DETAILITEM D ON R.RECEIPTNO = D.RECEIPTNO
    JOIN ALBUM A ON D.ALBUMNO = A.ALBUMNO
    JOIN SINGER S ON A.SINGERID = S.SINGERID
WHERE
    S.SINGERNAME = 'AFGAN'
    OR D.TAX = 0;